services:
  # Define o serviço como um site estático para o frontend.
  - type: web
    name: buzinas-eventos
    env: static
    plan: free # Especifica o plano gratuito do Render.
    # O comando de build que será executado a cada novo deploy.
    # Instala as dependências e depois executa o script "build" do package.json.
    buildCommand: npm install && npm run build
    # O diretório onde os arquivos estáticos compilados estão localizados.
    # O Vite, que adicionei ao projeto, usa 'dist' como padrão.
    staticPublishPath: dist
    # Regra para reescrever todas as requisições para o index.html,
    # o que é essencial para o funcionamento do roteamento no lado do cliente em SPAs (Single Page Applications).
    routes:
      - type: rewrite
        source: /*
        destination: /index.html